GET_RESPONSE_SUCCESS_CODE = 200
POST_RESPONSE_SUCCESS_CODE = 201
PUT_RESPONSE_SUCCESS_CODE = 204
DELETE_RESPONSE_SUCCESS_CODE = 204
NOT_FOUND_RESPONSE_CODE = 404
BAD_REQUEST_RESPONSE_CODE = 400
CONFLICT_RESPONSE_CODE = 409

SUCCESS_DESCRIPTION = "Success"
NOT_FOUND_DESCRIPTION = "Not Found"
BAD_REQUEST_DESCRIPTION = "Bad Request"
CONFLICT_DESCRIPTION = "Conflict"

JSON_MIME_TYPE = "application/json"
